#!/bin/bash

[ -n "$PS1" ] && source ~/.bash_profile

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/jkelly/.sdkman"
[[ -s "/Users/jkelly/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/jkelly/.sdkman/bin/sdkman-init.sh"

export PATH="$HOME/.yarn/bin:$PATH"
